version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.0

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run tests (basic check)
          command: echo "Project running"

      - run:
          name: SonarQube scan (dummy step)
          command: echo "SonarQube will run here"

workflows:
  build:
    jobs:
      - build